// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://namooagijjkmchscvsyt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5hbW9vYWdpamprbWNoc2N2c3l0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0MDkwMTYsImV4cCI6MjA2ODk4NTAxNn0.W2fNE5IPDbfYuNPeRtd7eTyBHhevwA55cYLdOSRUQwI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});